### ISSUE TITLE
napari nightly fails to run with pyside2 backend

### ISSUE THREAD

**Issue by psobolewskiPhD** [conda-forge/napari-feedstock#44]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

If the conda nightly of napari is installed with conda solver (which yields pyside2)
`conda create -n napari-main -c "napari/label/nightly" -c conda-forge napari python=3.10`
(see https://forum.image.sc/t/rotating-shapes-crashes-napari/78659/4?u=psobolewskiphd )
or with pyside2 forced using "napari=*=*pyside2*"  
then napari won't launch:
```
Validation errors in config file(s).
The following fields have been reset to the default value:

schema_version
  value is not a valid tuple (type=type_error.tuple)

Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/bin/napari", line 10, in <module>
    sys.exit(main())
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/lib/python3.10/site-packages/napari/__main__.py", line 449, in main
    _run()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/lib/python3.10/site-packages/napari/__main__.py", line 303, in _run
    splash = NapariSplashScreen()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/lib/python3.10/site-packages/napari/_qt/widgets/qt_splash_screen.py", line 10, in __init__
    get_app()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/lib/python3.10/site-packages/napari/_qt/qt_event_loop.py", line 195, in get_app
    _register_napari_resources()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/lib/python3.10/site-packages/napari/_qt/qt_resources/_icons.py", line 401, in _register_napari_resources
    resources = _compile_napari_resources(save_path=persist and save_path)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/lib/python3.10/site-packages/napari/_qt/qt_resources/_icons.py", line 338, in _compile_napari_resources
    output = compile_qrc(qrc)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/lib/python3.10/site-packages/napari/_qt/qt_resources/_icons.py", line 244, in compile_qrc
    return _compile_qrc_pyside2(qrc).replace(b'PySide2', b'qtpy')
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/lib/python3.10/site-packages/napari/_qt/qt_resources/_icons.py", line 229, in _compile_qrc_pyside2
    raise RuntimeError(f"PySide2 rcc binary not found in {pyside_root}")
RuntimeError: PySide2 rcc binary not found in /Users/piotrsobolewski/Dev/miniforge3/envs/napari-main/lib/python3.10/site-packages/PySide2
```

If pyqt is forced or mamba solver is used which installs pyqt, then everything works fine.

Curiously, if I manually install pyside2 and then install napari from the repo (`pip install .`), then napari also works.

### Installed packages

```shell
# packages in environment at /Users/piotrsobolewski/Dev/miniforge3/envs/napari-main:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
aom                       3.5.0                h7ea286d_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
arrow-cpp                 11.0.0          hce30654_13_cpu    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.6.26               h9ec8a34_1    conda-forge
aws-c-cal                 0.5.21               h134b2d6_2    conda-forge
aws-c-common              0.8.14               h1a8c8d9_0    conda-forge
aws-c-compression         0.2.16               h59b28b2_5    conda-forge
aws-c-event-stream        0.2.20               ha370d96_4    conda-forge
aws-c-http                0.7.6                hca61f3c_0    conda-forge
aws-c-io                  0.13.19              ha2443f3_3    conda-forge
aws-c-mqtt                0.8.6               hcd3fa0e_12    conda-forge
aws-c-s3                  0.2.7                hc514de9_1    conda-forge
aws-c-sdkutils            0.1.8                h59b28b2_0    conda-forge
aws-checksums             0.1.14               h59b28b2_5    conda-forge
aws-crt-cpp               0.19.8              h6be2766_12    conda-forge
aws-sdk-cpp               1.10.57              h3daea3c_8    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blosc                     1.21.3               h1d6ff8b_0    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
brotli                    1.0.9                h1a8c8d9_8    conda-forge
brotli-bin                1.0.9                h1a8c8d9_8    conda-forge
brotlipy                  0.7.0           py310h8e9501a_1005    conda-forge
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
c-blosc2                  2.8.0                h303ed30_1    conda-forge
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h2399d43_3    conda-forge
cfitsio                   4.2.0                h2f961c4_0    conda-forge
charls                    2.4.1                hb7217d7_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
cryptography              40.0.1          py310hfc83b78_0    conda-forge
cytoolz                   0.12.0          py310h8e9501a_1    conda-forge
dask                      2023.3.2           pyhd8ed1ab_0    conda-forge
dask-core                 2023.3.2           pyhd8ed1ab_0    conda-forge
dav1d                     1.0.0                he4db4b2_1    conda-forge
debugpy                   1.6.7           py310h0f1eb42_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
distributed               2023.3.2.1         pyhd8ed1ab_0    conda-forge
docstring_parser          0.15               pyhd8ed1ab_0    conda-forge
docutils                  0.19            py310hbe9552e_1    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hd633e50_1    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
fsspec                    2023.4.0           pyh1a96a4e_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
gflags                    2.2.2             hc88da5d_1004    conda-forge
giflib                    5.2.1                h1a8c8d9_3    conda-forge
glib                      2.74.1               hb5ab8b9_1    conda-forge
glib-tools                2.74.1               hb5ab8b9_1    conda-forge
glog                      0.6.0                h6da1cb0_0    conda-forge
gst-plugins-base          1.22.0               h8b7775e_2    conda-forge
gstreamer                 1.22.0               hcb7b3dd_2    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hsluv                     5.0.2              pyh44b312d_0    conda-forge
icu                       72.1                 he12128b_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2023.1.23       py310hcb660b6_2    conda-forge
imageio                   2.27.0             pyh24c5eb1_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.3.0              pyha770c72_0    conda-forge
importlib_metadata        6.3.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
ipykernel                 6.22.0             pyh736e0ef_0    conda-forge
ipython                   8.12.0             pyhd1c38e8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            8.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0           py310hbe9552e_0    conda-forge
jxrlib                    1.1                  h27ca646_2    conda-forge
kiwisolver                1.4.4           py310h2887b22_1    conda-forge
krb5                      1.20.1               h69eda48_0    conda-forge
lazy_loader               0.2                pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 hd835a16_1    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20230125.0      cxx17_hb7217d7_1    conda-forge
libaec                    1.0.6                hb7217d7_1    conda-forge
libarrow                  11.0.0          hdcd110a_13_cpu    conda-forge
libavif                   0.11.1               h3d80962_0    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_8    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_8    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_8    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libclang                  14.0.6          default_h81a5282_0    conda-forge
libclang13                14.0.6          default_he70ec0d_0    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   7.88.1               h9049daf_1    conda-forge
libcxx                    16.0.1               h75e25f2_0    conda-forge
libdeflate                1.18                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libevent                  2.1.10               h7673551_4    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libglib                   2.74.1               h4646484_1    conda-forge
libgoogle-cloud           2.8.0                h7206bc8_1    conda-forge
libgrpc                   1.52.1               he98ff75_1    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libjpeg-turbo             2.1.5.1              h1a8c8d9_0    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libllvm14                 14.0.6               hf6e71e7_1    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libogg                    1.3.4                h27ca646_1    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libopus                   1.3.1                h27ca646_1    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libpq                     15.2                 h1a28acd_0    conda-forge
libprotobuf               3.21.12              hb5ab8b9_0    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.40.0               h76d750c_0    conda-forge
libssh2                   1.10.0               h7a5bd25_3    conda-forge
libthrift                 0.18.1               h6635e49_0    conda-forge
libtiff                   4.5.0                h4f7d55c_6    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libvorbis                 1.3.7                h9f76cd9_0    conda-forge
libwebp-base              1.3.0                h1a8c8d9_0    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libxml2                   2.10.4               h2aff0a6_0    conda-forge
libxslt                   1.1.37               h1bd8bc4_0    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
libzopfli                 1.0.3                h9f76cd9_0    conda-forge
llvm-openmp               16.0.1               h7cfbb63_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.2           py310ha6df754_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
magicgui                  0.7.2              pyhd8ed1ab_0    conda-forge
markdown-it-py            2.2.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2           py310h8e9501a_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.5           py310h2887b22_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
mysql-common              8.0.32               h518ea0a_1    conda-forge
mysql-libs                8.0.32               hcb599eb_1    conda-forge
napari                    0.4.15.dev151   pyh92c539f_0_pyside2    napari/label/nightly
napari-console            0.0.8              pyhd8ed1ab_0    conda-forge
napari-plugin-engine      0.2.0              pyhd8ed1ab_2    conda-forge
napari-svg                0.1.6              pyhd8ed1ab_1    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
npe2                      0.6.2              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 hb7217d7_0    conda-forge
nss                       3.89                 h789eff7_0    conda-forge
numcodecs                 0.11.0          py310h0f1eb42_1    conda-forge
numpy                     1.24.2          py310h3d2048e_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                hbc2ba62_2    conda-forge
openssl                   3.1.0                h03a7124_0    conda-forge
orc                       1.8.3                hef0d403_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    2.0.0           py310h2b830bf_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.5.0           py310h07496d3_0    conda-forge
pint                      0.20.1             pyhd8ed1ab_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.2.0              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
psutil                    5.9.4           py310h8e9501a_0    conda-forge
psygnal                   0.8.1              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   11.0.0          py310h89f3c6b_13_cpu    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.7          py310h8e9501a_0    conda-forge
pygments                  2.15.0             pyhd8ed1ab_0    conda-forge
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyproject_hooks           1.0.0              pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3          py310h8e9501a_0    conda-forge
pyside2                   5.15.6          py310hbfa27b9_5    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.10         h3ba56d0_0_cpython    conda-forge
python-build              0.10.0             pyhd8ed1ab_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytomlpp                  1.0.13          py310h2887b22_0    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1           py310hf1a086a_0    conda-forge
pyyaml                    6.0             py310h8e9501a_5    conda-forge
pyzmq                     25.0.2          py310hc407298_0    conda-forge
qt-main                   5.15.8               h8c42f20_9    conda-forge
qtconsole-base            5.4.1              pyha770c72_0    conda-forge
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
re2                       2023.02.02           hb7217d7_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
rich                      13.3.3             pyhd8ed1ab_0    conda-forge
scikit-image              0.20.0          py310h2b830bf_0    conda-forge
scipy                     1.10.1          py310ha0d8a01_0    conda-forge
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
shellingham               1.5.1              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    6.1.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
superqt                   0.4.1              pyhd8ed1ab_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tifffile                  2023.3.21          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310h8e9501a_1    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typer                     0.4.2              pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
vispy                     0.12.2          py310hb614ae6_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.15.0          py310h8e9501a_0    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zarr                      2.14.2             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zfp                       1.0.0                hb6e4faa_3    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h03a7124_4    conda-forge
zlib-ng                   2.0.7                h1a8c8d9_0    conda-forge
zstd                      1.5.2                hf913c23_6    conda-forge
```

### Environment info

```shell
active environment : napari-main
    active env location : /Users/piotrsobolewski/Dev/miniforge3/envs/napari-main
            shell level : 2
       user config file : /Users/piotrsobolewski/.condarc
 populated config files : /Users/piotrsobolewski/Dev/miniforge3/.condarc
                          /Users/piotrsobolewski/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __osx=13.3.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/piotrsobolewski/Dev/miniforge3  (writable)
      conda av data dir : /Users/piotrsobolewski/Dev/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/piotrsobolewski/Dev/miniforge3/pkgs
                          /Users/piotrsobolewski/.conda/pkgs
       envs directories : /Users/piotrsobolewski/Dev/miniforge3/envs
                          /Users/piotrsobolewski/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.9.0 requests/2.27.1 CPython/3.10.8 Darwin/22.4.0 OSX/13.3.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by hmaarrfk** [comment]
hmm rcc stuff is a little weird in pyside2. The pip stuff is somewhat a hack to get all the path to workout.

https://github.com/conda-forge/pyside2-feedstock/blob/main/recipe/meta.yaml

We do have it at conda-forge.

I'm curious where the actual code that causes this is? I can't find any reference to `_compile_qrc_pyside2` in napari.

**Comment by psobolewskiPhD** [comment]
Hmm...
That code isn't in current napari...

I think I done played myself:

Looking at the env 
`napari                    0.4.15.dev151   pyh92c539f_0_pyside2    napari/label/nightly`
So it wasn't really a fresh nightly of napari at all 🤣 

With https://github.com/napari/napari/pull/3707 merged and released, this should be fixed.
I don't get why I (and the person needing help on image.sc) got 0.4.15dev though in March using conda classic solver. 

At present I can't reproduce with either mamba or conda (classic solver) and actual 0.5.0dev napari works fine with pyside2.
I'm going to close.
